{"settings": "d4bd6d6d215a168ed410309dc17e26f7", "version": "4.0.1", "files": {"graph_py": {"index": {"html_filename": "graph_py.html", "nums": [1, 119, 0, 14, 0, 0, 0], "relative_filename": "graph.py"}, "hash": "ae66c664d4da57c4410535ce883498ff"}, "graph_exceptions_py": {"index": {"html_filename": "graph_exceptions_py.html", "nums": [1, 11, 0, 2, 0, 0, 0], "relative_filename": "graph_exceptions.py"}, "hash": "9da5048bf852611a2f7a13f3b631cb11"}}, "format": 1}